run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - revive
    - errcheck
    - unused

issues:
  exclude-dirs:
    - tmp
    - res
    - outputDir

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: gioui\.org/app/internal/xkb
      linters:
        - govet
        - staticcheck
