run:
  timeout: 3m
  skip-dirs:
    - tmp
    - res
    - outputDir

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - revive
    - errcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
