run:
  timeout: 3m
  exclude_dirs:
    - tmp
    - res
    - outputDir

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - revive
    - errcheck
    - unused

issues:
  exclude-dirs:
    - tmp
    - res
    - outputDir
  exclude-rules:
    - path: gioui\.org/app/internal/xkb
