run:
  timeout: 5m
  go: "1.26"

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - revive
    - goimports
    - ineffassign
    - goconst
    - gocritic
    - gosimple
    - gosec
    - nilerr

issues:
  exclude-dirs:
    - tmp
    - res
    - outputDir

linters-settings:
  staticcheck:
    go: "1.26"
