// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/proto/v1/rates.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RatesService_StreamRates_FullMethodName = "/v1.RatesService/StreamRates"
)

// RatesServiceClient is the client API for RatesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RatesServiceClient interface {
	StreamRates(ctx context.Context, in *StreamRatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RateResponse], error)
}

type ratesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatesServiceClient(cc grpc.ClientConnInterface) RatesServiceClient {
	return &ratesServiceClient{cc}
}

func (c *ratesServiceClient) StreamRates(ctx context.Context, in *StreamRatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RatesService_ServiceDesc.Streams[0], RatesService_StreamRates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRatesRequest, RateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatesService_StreamRatesClient = grpc.ServerStreamingClient[RateResponse]

// RatesServiceServer is the server API for RatesService service.
// All implementations must embed UnimplementedRatesServiceServer
// for forward compatibility.
type RatesServiceServer interface {
	StreamRates(*StreamRatesRequest, grpc.ServerStreamingServer[RateResponse]) error
	mustEmbedUnimplementedRatesServiceServer()
}

// UnimplementedRatesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRatesServiceServer struct{}

func (UnimplementedRatesServiceServer) StreamRates(*StreamRatesRequest, grpc.ServerStreamingServer[RateResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamRates not implemented")
}
func (UnimplementedRatesServiceServer) mustEmbedUnimplementedRatesServiceServer() {}
func (UnimplementedRatesServiceServer) testEmbeddedByValue()                      {}

// UnsafeRatesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatesServiceServer will
// result in compilation errors.
type UnsafeRatesServiceServer interface {
	mustEmbedUnimplementedRatesServiceServer()
}

func RegisterRatesServiceServer(s grpc.ServiceRegistrar, srv RatesServiceServer) {
	// If the following call panics, it indicates UnimplementedRatesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RatesService_ServiceDesc, srv)
}

func _RatesService_StreamRates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RatesServiceServer).StreamRates(m, &grpc.GenericServerStream[StreamRatesRequest, RateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RatesService_StreamRatesServer = grpc.ServerStreamingServer[RateResponse]

// RatesService_ServiceDesc is the grpc.ServiceDesc for RatesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.RatesService",
	HandlerType: (*RatesServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRates",
			Handler:       _RatesService_StreamRates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/v1/rates.proto",
}
