// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/v1/rates.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyRate       string                 `protobuf:"bytes,1,opt,name=buyRate,proto3" json:"buyRate,omitempty"`
	SellRate      string                 `protobuf:"bytes,2,opt,name=sellRate,proto3" json:"sellRate,omitempty"`
	CantorId      int32                  `protobuf:"varint,3,opt,name=cantorId,json=cantorID,proto3" json:"cantorId,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	FetchedAt     int64                  `protobuf:"varint,5,opt,name=fetchedAt,proto3" json:"fetchedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	mi := &file_api_proto_v1_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rates_proto_rawDescGZIP(), []int{0}
}

func (x *RateResponse) GetBuyRate() string {
	if x != nil {
		return x.BuyRate
	}
	return ""
}

func (x *RateResponse) GetSellRate() string {
	if x != nil {
		return x.SellRate
	}
	return ""
}

func (x *RateResponse) GetCantorId() int32 {
	if x != nil {
		return x.CantorId
	}
	return 0
}

func (x *RateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RateResponse) GetFetchedAt() int64 {
	if x != nil {
		return x.FetchedAt
	}
	return 0
}

var File_api_proto_v1_rates_proto protoreflect.FileDescriptor

const file_api_proto_v1_rates_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/v1/rates.proto\x12\x02v1\"\x9a\x01\n" +
	"\fRateResponse\x12\x18\n" +
	"\abuyRate\x18\x01 \x01(\tR\abuyRate\x12\x1a\n" +
	"\bsellRate\x18\x02 \x01(\tR\bsellRate\x12\x1a\n" +
	"\bcantorId\x18\x03 \x01(\x05R\bcantorID\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1c\n" +
	"\tfetchedAt\x18\x05 \x01(\x03R\tfetchedAtB$Z\"github.com/Niutaq/Gix/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_rates_proto_rawDescOnce sync.Once
	file_api_proto_v1_rates_proto_rawDescData []byte
)

func file_api_proto_v1_rates_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rates_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rates_proto_rawDesc), len(file_api_proto_v1_rates_proto_rawDesc)))
	})
	return file_api_proto_v1_rates_proto_rawDescData
}

var file_api_proto_v1_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_proto_v1_rates_proto_goTypes = []any{
	(*RateResponse)(nil), // 0: v1.RateResponse
}
var file_api_proto_v1_rates_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rates_proto_init() }
func file_api_proto_v1_rates_proto_init() {
	if File_api_proto_v1_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rates_proto_rawDesc), len(file_api_proto_v1_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_v1_rates_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rates_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rates_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rates_proto = out.File
	file_api_proto_v1_rates_proto_goTypes = nil
	file_api_proto_v1_rates_proto_depIdxs = nil
}
