// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/v1/rates.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuyRate       string                 `protobuf:"bytes,1,opt,name=buyRate,proto3" json:"buyRate,omitempty"`
	SellRate      string                 `protobuf:"bytes,2,opt,name=sellRate,proto3" json:"sellRate,omitempty"`
	CantorId      int32                  `protobuf:"varint,3,opt,name=cantorId,json=cantorID,proto3" json:"cantorId,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	FetchedAt     int64                  `protobuf:"varint,5,opt,name=fetchedAt,proto3" json:"fetchedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateResponse) Reset() {
	*x = RateResponse{}
	mi := &file_api_proto_v1_rates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateResponse) ProtoMessage() {}

func (x *RateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateResponse.ProtoReflect.Descriptor instead.
func (*RateResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rates_proto_rawDescGZIP(), []int{0}
}

func (x *RateResponse) GetBuyRate() string {
	if x != nil {
		return x.BuyRate
	}
	return ""
}

func (x *RateResponse) GetSellRate() string {
	if x != nil {
		return x.SellRate
	}
	return ""
}

func (x *RateResponse) GetCantorId() int32 {
	if x != nil {
		return x.CantorId
	}
	return 0
}

func (x *RateResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RateResponse) GetFetchedAt() int64 {
	if x != nil {
		return x.FetchedAt
	}
	return 0
}

type HistoryPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	BuyRate       float64                `protobuf:"fixed64,2,opt,name=buyRate,proto3" json:"buyRate,omitempty"`
	SellRate      float64                `protobuf:"fixed64,3,opt,name=sellRate,proto3" json:"sellRate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryPoint) Reset() {
	*x = HistoryPoint{}
	mi := &file_api_proto_v1_rates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryPoint) ProtoMessage() {}

func (x *HistoryPoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryPoint.ProtoReflect.Descriptor instead.
func (*HistoryPoint) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rates_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryPoint) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *HistoryPoint) GetBuyRate() float64 {
	if x != nil {
		return x.BuyRate
	}
	return 0
}

func (x *HistoryPoint) GetSellRate() float64 {
	if x != nil {
		return x.SellRate
	}
	return 0
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*HistoryPoint        `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_api_proto_v1_rates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rates_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryResponse) GetPoints() []*HistoryPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *HistoryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type StreamRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []string               `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRatesRequest) Reset() {
	*x = StreamRatesRequest{}
	mi := &file_api_proto_v1_rates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRatesRequest) ProtoMessage() {}

func (x *StreamRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_rates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRatesRequest.ProtoReflect.Descriptor instead.
func (*StreamRatesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_rates_proto_rawDescGZIP(), []int{3}
}

func (x *StreamRatesRequest) GetCurrencies() []string {
	if x != nil {
		return x.Currencies
	}
	return nil
}

var File_api_proto_v1_rates_proto protoreflect.FileDescriptor

const file_api_proto_v1_rates_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/v1/rates.proto\x12\x02v1\"\x9a\x01\n" +
	"\fRateResponse\x12\x18\n" +
	"\abuyRate\x18\x01 \x01(\tR\abuyRate\x12\x1a\n" +
	"\bsellRate\x18\x02 \x01(\tR\bsellRate\x12\x1a\n" +
	"\bcantorId\x18\x03 \x01(\x05R\bcantorID\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1c\n" +
	"\tfetchedAt\x18\x05 \x01(\x03R\tfetchedAt\"X\n" +
	"\fHistoryPoint\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x18\n" +
	"\abuyRate\x18\x02 \x01(\x01R\abuyRate\x12\x1a\n" +
	"\bsellRate\x18\x03 \x01(\x01R\bsellRate\"W\n" +
	"\x0fHistoryResponse\x12(\n" +
	"\x06points\x18\x01 \x03(\v2\x10.v1.HistoryPointR\x06points\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"4\n" +
	"\x12StreamRatesRequest\x12\x1e\n" +
	"\n" +
	"currencies\x18\x01 \x03(\tR\n" +
	"currencies2I\n" +
	"\fRatesService\x129\n" +
	"\vStreamRates\x12\x16.v1.StreamRatesRequest\x1a\x10.v1.RateResponse0\x01B$Z\"github.com/Niutaq/Gix/api/proto/v1b\x06proto3"

var (
	file_api_proto_v1_rates_proto_rawDescOnce sync.Once
	file_api_proto_v1_rates_proto_rawDescData []byte
)

func file_api_proto_v1_rates_proto_rawDescGZIP() []byte {
	file_api_proto_v1_rates_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_rates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_rates_proto_rawDesc), len(file_api_proto_v1_rates_proto_rawDesc)))
	})
	return file_api_proto_v1_rates_proto_rawDescData
}

var file_api_proto_v1_rates_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_v1_rates_proto_goTypes = []any{
	(*RateResponse)(nil),       // 0: v1.RateResponse
	(*HistoryPoint)(nil),       // 1: v1.HistoryPoint
	(*HistoryResponse)(nil),    // 2: v1.HistoryResponse
	(*StreamRatesRequest)(nil), // 3: v1.StreamRatesRequest
}
var file_api_proto_v1_rates_proto_depIdxs = []int32{
	1, // 0: v1.HistoryResponse.points:type_name -> v1.HistoryPoint
	3, // 1: v1.RatesService.StreamRates:input_type -> v1.StreamRatesRequest
	0, // 2: v1.RatesService.StreamRates:output_type -> v1.RateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_v1_rates_proto_init() }
func file_api_proto_v1_rates_proto_init() {
	if File_api_proto_v1_rates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_rates_proto_rawDesc), len(file_api_proto_v1_rates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_rates_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_rates_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_rates_proto_msgTypes,
	}.Build()
	File_api_proto_v1_rates_proto = out.File
	file_api_proto_v1_rates_proto_goTypes = nil
	file_api_proto_v1_rates_proto_depIdxs = nil
}
