// Code generated by protoc-gen-go-drpc. DO NOT EDIT.
// protoc-gen-go-drpc version: v0.0.34
// source: api/proto/v1/rates.proto

package v1

import (
	context "context"
	errors "errors"
	protojson "google.golang.org/protobuf/encoding/protojson"
	proto "google.golang.org/protobuf/proto"
	drpc "storj.io/drpc"
	drpcerr "storj.io/drpc/drpcerr"
)

type drpcEncoding_File_api_proto_v1_rates_proto struct{}

func (drpcEncoding_File_api_proto_v1_rates_proto) Marshal(msg drpc.Message) ([]byte, error) {
	return proto.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_api_proto_v1_rates_proto) MarshalAppend(buf []byte, msg drpc.Message) ([]byte, error) {
	return proto.MarshalOptions{}.MarshalAppend(buf, msg.(proto.Message))
}

func (drpcEncoding_File_api_proto_v1_rates_proto) Unmarshal(buf []byte, msg drpc.Message) error {
	return proto.Unmarshal(buf, msg.(proto.Message))
}

func (drpcEncoding_File_api_proto_v1_rates_proto) JSONMarshal(msg drpc.Message) ([]byte, error) {
	return protojson.Marshal(msg.(proto.Message))
}

func (drpcEncoding_File_api_proto_v1_rates_proto) JSONUnmarshal(buf []byte, msg drpc.Message) error {
	return protojson.Unmarshal(buf, msg.(proto.Message))
}

type DRPCRatesServiceClient interface {
	DRPCConn() drpc.Conn

	StreamRates(ctx context.Context, in *StreamRatesRequest) (DRPCRatesService_StreamRatesClient, error)
}

type drpcRatesServiceClient struct {
	cc drpc.Conn
}

func NewDRPCRatesServiceClient(cc drpc.Conn) DRPCRatesServiceClient {
	return &drpcRatesServiceClient{cc}
}

func (c *drpcRatesServiceClient) DRPCConn() drpc.Conn { return c.cc }

func (c *drpcRatesServiceClient) StreamRates(ctx context.Context, in *StreamRatesRequest) (DRPCRatesService_StreamRatesClient, error) {
	stream, err := c.cc.NewStream(ctx, "/v1.RatesService/StreamRates", drpcEncoding_File_api_proto_v1_rates_proto{})
	if err != nil {
		return nil, err
	}
	x := &drpcRatesService_StreamRatesClient{stream}
	if err := x.MsgSend(in, drpcEncoding_File_api_proto_v1_rates_proto{}); err != nil {
		return nil, err
	}
	if err := x.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DRPCRatesService_StreamRatesClient interface {
	drpc.Stream
	Recv() (*RateResponse, error)
}

type drpcRatesService_StreamRatesClient struct {
	drpc.Stream
}

func (x *drpcRatesService_StreamRatesClient) GetStream() drpc.Stream {
	return x.Stream
}

func (x *drpcRatesService_StreamRatesClient) Recv() (*RateResponse, error) {
	m := new(RateResponse)
	if err := x.MsgRecv(m, drpcEncoding_File_api_proto_v1_rates_proto{}); err != nil {
		return nil, err
	}
	return m, nil
}

func (x *drpcRatesService_StreamRatesClient) RecvMsg(m *RateResponse) error {
	return x.MsgRecv(m, drpcEncoding_File_api_proto_v1_rates_proto{})
}

type DRPCRatesServiceServer interface {
	StreamRates(*StreamRatesRequest, DRPCRatesService_StreamRatesStream) error
}

type DRPCRatesServiceUnimplementedServer struct{}

func (s *DRPCRatesServiceUnimplementedServer) StreamRates(*StreamRatesRequest, DRPCRatesService_StreamRatesStream) error {
	return drpcerr.WithCode(errors.New("Unimplemented"), drpcerr.Unimplemented)
}

type DRPCRatesServiceDescription struct{}

func (DRPCRatesServiceDescription) NumMethods() int { return 1 }

func (DRPCRatesServiceDescription) Method(n int) (string, drpc.Encoding, drpc.Receiver, interface{}, bool) {
	switch n {
	case 0:
		return "/v1.RatesService/StreamRates", drpcEncoding_File_api_proto_v1_rates_proto{},
			func(srv interface{}, ctx context.Context, in1, in2 interface{}) (drpc.Message, error) {
				return nil, srv.(DRPCRatesServiceServer).
					StreamRates(
						in1.(*StreamRatesRequest),
						&drpcRatesService_StreamRatesStream{in2.(drpc.Stream)},
					)
			}, DRPCRatesServiceServer.StreamRates, true
	default:
		return "", nil, nil, nil, false
	}
}

func DRPCRegisterRatesService(mux drpc.Mux, impl DRPCRatesServiceServer) error {
	return mux.Register(impl, DRPCRatesServiceDescription{})
}

type DRPCRatesService_StreamRatesStream interface {
	drpc.Stream
	Send(*RateResponse) error
}

type drpcRatesService_StreamRatesStream struct {
	drpc.Stream
}

func (x *drpcRatesService_StreamRatesStream) Send(m *RateResponse) error {
	return x.MsgSend(m, drpcEncoding_File_api_proto_v1_rates_proto{})
}
