# k8s/01-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gix-config
data:
  POSTGRES_DB: "gix_rates"
  POSTGRES_USER: "gixuser"
  REDIS_URL: "redis://gix-redis:6379/0"
  SWAGGER_HOST: "165.227.246.100:8080" # TODO: Change to your domain or dynamic IP